### ISSUE TITLE
Runtime error when running Excess Power of server.

### ISSUE THREAD

**Issue by vincentdumont** [GNOME-physics/gdas#4]
I get the following runtime error message when running the excess power module on the Jupyter Hub"

```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    gdas.excess_power(ts_data,psd_segment_length,psd_segment_stride,psd_estimation,window_fraction,tile_fap,station,nchans=channels)
  File "/usr/local/lib/python2.7/dist-packages/gdas/epower.py", line 52, in excess_power
    seg_len,fd_psd,lal_psd = calculate_psd(ts_data,sample_rate,psd_segment_length,psd_segment_stride,psd_estimation)
  File "/usr/local/lib/python2.7/dist-packages/gdas/epower.py", line 196, in calculate_psd
    data = ts_data.astype(numpy.float64)
  File "<decorator-gen-236>", line 2, in astype
  File "/usr/local/lib/python2.7/dist-packages/pycbc/types/array.py", line 213, in _returntype
    return self._return(ary)
  File "/usr/local/lib/python2.7/dist-packages/pycbc/types/timeseries.py", line 88, in _return
    return TimeSeries(ary, self._delta_t, epoch=self._epoch, copy=False)
  File "/usr/local/lib/python2.7/dist-packages/pycbc/types/timeseries.py", line 83, in __init__
    Array.__init__(self, initial_array, dtype=dtype, copy=copy)
  File "/usr/local/lib/python2.7/dist-packages/pycbc/types/array.py", line 138, in __init__
    if not _scheme_matches_base_array(initial_array):
  File "<decorator-gen-126>", line 2, in _scheme_matches_base_array
  File "/usr/local/lib/python2.7/dist-packages/pycbc/scheme.py", line 188, in scheming_function
    raise RuntimeError(err)
RuntimeError: Failed to find implementation of (<function _scheme_matches_base_array at 0x7f1f7fcfbaa0>) for cpu scheme.
```

The same packages' version is used in my personal laptop and I don't get the problem. I suspect something is wrong with the server...

**Comment by vincentdumont** [comment]
The issue can be fixed by using Scipy 0.18. Later versions are introducing some incompatibilities. In order for the gdas scripts to work, one must use 0.18 or earlier versions of Scipy.
